---
- name: gpsd setup
  hosts: gpsd
  become: yes

  tasks:

    - name: Update repo and cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install packages with apt
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - python3
        - ntp
        - pps-tools
        - gpsd
        - gpsd-clients

    - name: Update config file for GPSD
      template:
        src: gpsd.j2
        dest: /etc/default/gpsd

    - name: Make sure gpsd is restarted and running
      systemd:
        name: gpsd
        daemon_reload: true
        enabled: true
        state: restarted