---
- name: gpsd setup
  hosts: gpsd
  become: yes

  tasks:

    - name: Update repo and cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install packages with apt
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - python3
        - ntp
        - pps-tools
        - gpsd
        - gpsd-clients

    - name: Update config file for GPSD
      copy:
        src: templates/gpsd.conf
        dest: /etc/default/gpsd
      notify:
        - restart gpsd

    - name: Update config file for NTP
      copy:
        src: templates/ntp.conf
        dest: /etc/ntp.conf
      notify:
        - restart ntp

    - name: Copy clockmaker script
      copy:
        src: utils/clockmaker
        dest: /home/pi/clockmaker

  handlers:
      - name: restart gpsd
        systemd:
          name: gpsd
          daemon_reload: true
          enabled: true
          state: restarted

      - name: restart ntp
        systemd:
          name: ntp
          daemon_reload: true
          enabled: true
          state: restarted

# Add to /boot/config.txt
# Enable PPS on GPIO4
# dtoverlay=pps-gpio,gpiopin=4
