---
- name: gpsd setup
  hosts: gpsd
  become: yes

  tasks:

    - name: Set hostname
      ansible.builtin.hostname:
        name: pi42

    # - name: Make sure hciuart is disabled and stopped
    #     systemd:
    #       name: hciuart
    #       enabled: false
    #       state: stopped
  
    # - name: Make sure serial-getty@ttyAMA0.service is disabled and stopped
    #   systemd:
    #     name: serial-getty@ttyAMA0.service
    #     enabled: false
    #     state: stopped

    - name: Update repo and cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install packages with apt
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - python3
        - ntp
        - pps-tools
        - gpsd
        - gpsd-clients

    - name: Update config file for GPSD
      copy:
        src: templates/gpsd.conf
        dest: /etc/default/gpsd
      notify:
        - restart gpsd

    - name: Update config file for NTP
      copy:
        src: templates/ntp.conf
        dest: /etc/ntp.conf
      notify:
        - restart ntp

    - name: enable GPS PPS on boot
      blockinfile:
        path: /boot/config.txt
        block: |
          # Get 1PPS from HAT pin
          dtoverlay=pps-gpio,gpiopin=4
          # Reduce GPU memory split
          gpu_mem=16

    ##### Find a way to disable the serial console

    # - name: Copy clockmaker script
    #   copy:
    #     src: utils/clockmaker
    #     dest: /home/pi/clockmaker

  handlers:
      - name: restart gpsd
        systemd:
          name: gpsd
          daemon_reload: true
          enabled: true
          state: restarted

      - name: restart ntp
        systemd:
          name: ntp
          daemon_reload: true
          enabled: true
          state: restarted

# Add to /boot/config.txt
# Enable PPS on GPIO4
# dtoverlay=pps-gpio,gpiopin=4
